language: python
python: '3.6'

stages:
#  - create vunit/run images
  - dockerized vunit
  - test
  - build and update gh-pages

install:
  - git fetch --unshallow --tags
  - pip install tox

script: tox -e $BUILD_NAME

env:
  matrix:
    - BUILD_NAME=py36-unit
    - BUILD_NAME=py36-lint
    - BUILD_NAME=py36-docs

jobs:
  include:
  - env: BUILD_NAME=py27-unit
    python: '2.7'
  - env: BUILD_NAME=py27-lint
    python: '2.7'
  - env: BUILD_NAME=py27-docs
    python: '2.7'

  - env: BUILD_NAME=py34-unit
    python: '3.4'
  - env: BUILD_NAME=py35-unit
    python: '3.5'

  # Python 2.7 with ghdl mcode
  - env: BUILD_NAME=py27-acceptance-ghdl
    python: '2.7'
    os: linux
    sudo: false
    addons:
      apt:
        packages: gnat
    before_script:
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-mcode
    - cd build-mcode
    - ../configure --prefix=../../install-ghdl-mcode/
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-mcode/bin/

  # Python 3.6 with ghdl llvm
  - env: BUILD_NAME=py36-acceptance-ghdl
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gnat-4.8 zlib1g-dev
    - sudo apt-get install -y llvm-3.5-dev llvm-3.5-tools libedit-dev
    before_script:
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-llvm
    - cd build-llvm
    - ../configure --prefix=../../install-ghdl-llvm/ --with-llvm-config=llvm-config-3.5
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-llvm/bin/

  # Python 2.7 with ghdl mcode in docker containers
  - &acceptance
    stage: dockerized vunit
    env:
      - BUILD_NAME=py27-acceptance-ghdl
      - VUNIT_RUN_IMG="vunit/run:2-alpine3.7"
      - VUNIT_SIM_IMG="ghdl/ghdl:stretch-mcode"
    python: '2.7'
    os: linux
    sudo: required
    dist: trusty
    addons:
      apt:
        packages:
        - docker-ce
    services: docker
    before_script: pip install -r requirements.txt
    script: VUNIT_DIR=$(pwd) python examples/vhdl/array/run.py -d -v

  # Python 3.6 with ghdl llvm in docker containers
  - <<: *acceptance
    env:
      - BUILD_NAME=py36-acceptance-ghdl
      - VUNIT_RUN_IMG="vunit/run:3.6-alpine"
      - VUNIT_SIM_IMG="ghdl/ghdl:ubuntu18-llvm-5.0"
    python: '3.6'
    script: VUNIT_DIR=$(pwd) python examples/vhdl/array/run.py -d -v

  # Deploy to GitHub pages
  - stage: deploy
    python: '3.6'
    script:
      - tox -e py36-docs
      - touch .tox/py36-docs/tmp/docsbuild/.nojekyll
    deploy:
      edge:
        branch: v1.8.47
      provider: pages
      repo: VUnit/VUnit.github.io
      target_branch: master
      local_dir: .tox/py36-docs/tmp/docsbuild/
      # This environment variable is set to an OAuth token in travis vunit settings
      github_token: $GITHUB_PAGES_TOKEN
      skip_cleanup: true
      on:
        branch: master

  # Deploy to PyPI whenever the package version has changed
  # When a package version has not changed a new upload will not be triggered
  - stage: deploy
    python: '3.6'
    script:
      - sed -i "s/PRE_RELEASE = True/PRE_RELEASE = False/" vunit/about.py
      - python tools/is_new_release.py release_name is_new_release
      - export IS_NEW_RELEASE=`cat is_new_release`
      - export RELEASE_NAME=`cat release_name`

    deploy:
      - provider: pypi
        distributions: sdist
        skip_cleanup: true
        skip_upload_docs: true
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        on:
          branch: master
          condition: $IS_NEW_RELEASE = True

#      - provider: releases
#        skip_cleanup: true
#        api_key:
#          secure: VzowiHBE7Lc14p/QOFvYYLz65g1uvYvffv32F2AVlpt4hs0EAdqME2+BLPnDDI1D4Oou30VXs2p37doI0J2qyyiT5TbSFzErYz+7uREYEOBWR5IQsK/iQrSxKOZ2Ox558T1zcObnZhVjAbV1yxQhdqitSWBCpayuNl4Gvubc0S1+MXhh/psvLgJ/r2Nq5gCAaoqmxvHUoNotQWYF5hKzynXPvV0wniB2l2HKc/UMK7jIu+GRKwMWk1NXuBk5ocreoAVrSH/FHD87K8wUfUqgaGjYRaniKbl2etMw4kcfRC1J+WtcUzVeHtb2tnlHo1Qk1tE7Dt5LMWYp0RlpiLfHmu4attHn2jdKBwdetGiB+admq7D6K0bROVQw6l1kJNYNROXR9PhA6ZkYQvDY1iF+RmikUee8zpGEZE0Ux1RjlCBAOE+yJu3/TWJpO3KCFEYKELqmljOgpaAu/ogyowLwDtakjzK1nA34CmgN9xwgARuxbzQNPxMIlFBeH4QJ9qMj3Jo9jUOxKF4dtSF5Y2t8p4XZ4RDBAwMb4QB35BaWCd7u2UwCVbks3CR7mdFXT22ZjN+92kgFOsqhsK67cNCXuUhL3jDAQ5His4qqca2+A25BVDFG3qz673gZotIq4/MYcBZx7daNJN88dFH47Rx8SDtiu7mb/6Y7TMaf7zW/KEs=
#        file: "ghdl-*.tgz"
#        file_glob: true
#        on:
#          repo: 1138-4EB/vunit
#          all_branches: true
#          tags: true
#
#  - stage: create vunit/run images
#    <<: *acceptance
#    env:  BUILD_NAME="run images"
#    language: minimal
#    install: skip
#    before_script:
#    script: ./docker/build_run_images.sh
#    addons:
#      apt:
#        packages: docker-ce
