language: python
install: pip install tox
script: tox -e $BUILD_NAME

stages:
  - test
  - deploy

matrix:
  include:
  - &docker
    env:
      - BUILD_NAME=py27-acceptance-ghdl
      - DOCKER_IMAGE=mcode-2
    services: docker
    language: minimal
    install: skip
    script: docker run --rm -tv $(pwd):/src -w /src vunit/dev:$DOCKER_IMAGE tox -e $BUILD_NAME

  - <<: *docker
    env:
      - BUILD_NAME=py37-acceptance-ghdl
      - DOCKER_IMAGE=llvm

  - <<: *docker
    env:
      - BUILD_NAME=py37-vcomponents-ghdl
      - DOCKER_IMAGE=mcode


  - env: BUILD_NAME=py27-lint
    python: '2.7'
  - env: BUILD_NAME=py37-lint
    dist: xenial
    python: '3.7'


  - env: BUILD_NAME=py27-unit
    python: '2.7'
  - env: BUILD_NAME=py34-unit
    python: '3.4'
  - env: BUILD_NAME=py35-unit
    python: '3.5'
  - env: BUILD_NAME=py36-unit
    python: '3.6'
  - env: BUILD_NAME=py37-unit
    dist: xenial
    python: '3.7'


  - env: BUILD_NAME=py27-docs
    python: '2.7'
    before_script: git fetch --unshallow --tags
  - env:
      - BUILD_NAME=py36-docs
      - DOCKER_IMAGE=mcode
    python: '3.6'
    before_script:
      - git fetch --unshallow --tags
      - git clone https://github.com/VUnit/vc_uart && mv vc_uart ..
      - git clone https://github.com/VUnit/vc_axi && mv vc_axi ..
    after_success: touch .tox/py36-docs/tmp/docsbuild/.nojekyll
    deploy:
      provider: pages
      target_branch: gh-pages
      local_dir: .tox/py36-docs/tmp/docsbuild/
      # This environment variable is set to an OAuth token in travis vunit settings
      github_token: $GITHUB_PAGES_TOKEN
      skip_cleanup: true
      on:
        repo: 1138-4EB/vunit
        branch: site-rework
        #tags: true

  # Deploy to PyPI whenever the package version has changed
  # When a package version has not changed a new upload will not be triggered
  - stage: deploy
    python: '3.6'
    if: tag IS present
    script:
      - git fetch --unshallow --tags
      - python tools/new_release.py 'check'
    deploy:
      provider: pypi
      distributions: sdist
      skip_cleanup: true
      skip_upload_docs: true
      user: $PYPI_USER
      password: $PYPI_PASSWORD
      on:
        repo: VUnit/vunit
        branch: master
